<<<

[[_orderShipments]]
== Order Shipments

Listed below are Miva XML Provisioning Tags for creating shipments and marking an order as shipped, with tracking number and carrier information. First, you need create a shipment of the products in the order. This can be a single shipment that would contain all products in the order, or you can choose to create a shipment that only contains some of the products in the order (Ex: the order contains multiple shipments).

[[_createShipment]]
=== Create Shipment

Create an order shipment.

==== Schema
[options="header",cols="35%,12%,10%,15%,28%"]
|===
|Element Xpath|Required|Occurs|Type|Description
|OrderShipment_Add|Yes|1|Container Node|Top-level container.
|OrderShipment_Add `@order_id`|Yes|1|Integer Attribute|The target order id.
|OrderShipment_Add/ProductList|Yes|1|Container Node|Container node for shipment product list.
|OrderShipment_Add/ProductList/Product|Yes|1+|Self-Closing Node|Shipment product list item.
|OrderShipment_Add/ProductList/Product `@line_id`|Yes|1+|Text Attribute|Product list item's line id.
|OrderShipment_Add/ProductList/Product `@quantity`|Yes|1+|Integer Attribute|Quantity of product list item included in shipment.
|OrderShipment_Add/Code|Yes|1|Text Node|Identifier code for shipment. This must be a `unique` value.
|===

<<<

==== Create Shipment Examples

[source,xml]
----
<OrderShipment_Add order_id="1000">
    <ProductList>
        <Product line_id="test" quantity="1"/>
    </ProductList>
    <Code>1000-1</Code>
</OrderShipment_Add>
<OrderShipment_Add order_id="1000">
    <ProductList>
        <Product line_id="test2" quantity="1"/>
        <Product line_id="test3" quantity="2"/>
    </ProductList>
    <Code>1000-2</Code>
</OrderShipment_Add>
----


[[_updateShipment]]
=== Update Shipment

Update an existing order shipment with tracking information, shipping date information, and/or flag shipment as shipped. Depending on the settings setup in Miva for the Shipment Emails, the `OrderShipment_SetStatus` tag will also trigger a Shipment Shipped Email to the customer. However, this can be turned off if the ERP system needs to send this email.

==== Schema
[options="header",cols="35%,12%,10%,15%,28%"]
|===
|Element Xpath|Required|Occurs|Type|Description
|OrderShipment_SetStatus|Yes|1|Container Node|Top-level container.
|OrderShipment_SetStatus `@code`|Yes|1|Text Attribute|The target shipment code.
|OrderShipment_SetStatus/MarkAsShipped|No|1|Boolean Node|Mark the shipment as shipped.

Accepted values: +
- `1` +
- `Yes`
|OrderShipment_SetStatus/TrackingNumber|No|1|Text Node|Tracking number from shipping carrier.
|OrderShipment_SetStatus/TrackingType|No|1|Text Node|Used to determine the link used in the Shipment Shipped Email.

Possible values: +
- `CanadaPost` +
- `Endicia` +
- `FedEx` +
- `UPS` +
- `USPS`

|OrderShipment_SetStatus/ShipDate|No|1|Container Node|Container node for shipment date.
|OrderShipment_SetStatus/ShipDate/Day|Yes*|1|Text Node|Shipment day of month.
|OrderShipment_SetStatus/ShipDate/Month|Yes*|1|Text Node|Shipment month of year.
|OrderShipment_SetStatus/ShipDate/Year|Yes*|1|Text Node|Shipment year.
|OrderShipment_SetStatus/ShipDate/Hour|No|1|Text Node|Shipment hour of day.
|OrderShipment_SetStatus/ShipDate/Minute|No|1|Text Node|Shipment minute of hour.
|OrderShipment_SetStatus/ShipDate/Second|No|1|Text Node|Shipment second of minute.
|===

<<<

==== Update Shipment Examples

[source,xml]
----
<OrderShipment_SetStatus code="1000-1">
    <MarkAsShipped>1</MarkAsShipped>
    <TrackingNumber>0123456</TrackingNumber>
    <TrackingType>UPS</TrackingType>
    <ShipDate>
        <Year>2017</Year>
        <Month>05</Month>
        <Day>09</Day>
        <Hour>12</Hour>
        <Minute>30</Minute>
        <Second>30</Second>
    </ShipDate>
</OrderShipment_SetStatus>
----
